name: Pull Request

on:
    pull_request_target:

permissions:
    contents: write
    pull-requests: write

jobs:
    CodeStyle:
        name: CodeStyle
        runs-on: ubuntu-latest
        steps:
          - name: CodeStyle
            uses: EncoreDigitalGroup/ci-workflows/actions/php/codeStyle@v2
            with:
              branch: "${{ github.head_ref }}"
              repository: "${{ github.repository }}"

    StaticAnalysis:
        needs: CodeStyle
        name: StaticAnalysis
        uses: EncoreDigitalGroup/ci-workflows/.github/workflows/php_larastan.yml@v2
        with:
          path: 'src/'
          branch: ${{ github.head_ref }}
          
    Test:
        needs: CodeStyle
        name: Test
        uses: EncoreDigitalGroup/ci-workflows/.github/workflows/php_pest.yml@v2
        with:
          branch: ${{ github.head_ref }}
          runParallel: true

    AutoMerge:
        needs: [ StaticAnalysis, Test ]
        name: Auto-Merge
        uses: EncoreDigitalGroup/ci-workflows/.github/workflows/github_dependabotAutoMerge.yml@v2
