name: Pull Request

on:
    pull_request_target:

permissions:
    contents: write
    pull-requests: write

jobs:
    Duster:
        name: Duster
        uses: EncoreDigitalGroup/.github/.github/workflows/duster-fix-blame.yml@main
        permissions:
            contents: write
            pull-requests: write
    StaticAnalysis:
        needs: Duster
        name: RunLarastan
        uses: EncoreDigitalGroup/.github/.github/workflows/larastan.yml@main
        with:
            path: 'src/'
    UnitTests:
        needs: StaticAnalysis
        name: UnitTests
        uses: EncoreDigitalGroup/.github/.github/workflows/pest.yml@main
        with:
            phpVersion: '8.3'
    AutoMerge:
        needs: UnitTests
        name: AutoMerge
        uses: EncoreDigitalGroup/.github/.github/workflows/dependabot-auto-merge.yml@main
