name: Pull Request

on:
    pull_request_target:

permissions:
    contents: write
    pull-requests: write

jobs:
    Duster:
        name: Duster
        uses: EncoreDigitalGroup/.github/.github/workflows/dusterFixBlame.yml@latest
        permissions:
            contents: write
            pull-requests: write

    StaticAnalysis:
        needs: Duster
        name: StaticAnalysis
        uses: EncoreDigitalGroup/.github/.github/workflows/larastan.yml@latest
        with:
            path: 'src/'

    UnitTests:
        needs: StaticAnalysis
        name: UnitTests
        uses: EncoreDigitalGroup/.github/.github/workflows/pest.yml@latest
        with:
            phpVersion: '8.3'

    AutoMerge:
        needs: UnitTests
        name: AutoMerge
        uses: EncoreDigitalGroup/.github/.github/workflows/dependabotAutoMerge.yml@latest