name: Release

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
      - '!v[0-9]+.[0-9]+.[0-9]+-rc[0-9]+'

jobs:
  CreateRelease:
    name: CreateRelease
    uses: EncoreDigitalGroup/.github/.github/workflows/createRelease.yml@latest
    with:
      generate_release_notes: true
      is_draft: false
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}